import { useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, LockKeyhole, Sparkles } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { Badge, Card, LoadingSpinner } from "../components/ui";
import { api, authUrl } from "../services/api";

export function LoginPage() {
  const [configured, setConfigured] = useState<boolean | null>(null);
  const [searchParams] = useSearchParams();
  useEffect(() => { void api.auth.status().then((status) => setConfigured(status.ready)).catch(() => setConfigured(false)); }, []);
  const callbackError = searchParams.get("error");
  const errorMessage = callbackError === "oauth_not_configured" ? "Add your Google OAuth and PostgreSQL settings to server/.env to enable sign-in." : callbackError ? "Google sign-in could not be completed. Please try again." : "";
  return <main className="mx-auto grid min-h-[75vh] max-w-6xl place-items-center px-5 py-16"><Card className="grid w-full max-w-4xl overflow-hidden md:grid-cols-2"><div className="bg-slate-950 p-8 text-white sm:p-12"><Link to="/" className="inline-flex items-center gap-2 text-sm text-slate-300"><ArrowLeft size={15}/> Back home</Link><span className="mt-16 grid h-12 w-12 place-items-center rounded-2xl bg-lime-300 text-slate-950"><Sparkles/></span><h1 className="mt-7 text-3xl font-semibold tracking-tight">Your next level<br/>is waiting.</h1><p className="mt-4 text-sm leading-6 text-slate-400">A dedicated space for your sport, your goals and the progress you’re working toward.</p><div className="mt-12 text-xs text-slate-500">STRIVE · PHASE 2 · GOOGLE SIGN-IN</div></div><div className="flex flex-col justify-center p-8 sm:p-12"><Badge className="w-fit">Secure account access</Badge><h2 className="mt-5 text-2xl font-semibold">Welcome to Strive</h2><p className="mt-3 text-sm leading-6 text-slate-600">Sign in with Google to save your training profile and continue to your dashboard.</p>{errorMessage && <p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-900" role="alert">{errorMessage}</p>}{configured === null ? <div className="mt-7"><LoadingSpinner label="Checking sign-in setup"/></div> : configured ? <a href={authUrl} className="mt-7 inline-flex w-full items-center justify-between rounded-xl bg-lime-300 px-5 py-3 text-sm font-semibold text-slate-950 transition hover:bg-lime-200"><span className="flex items-center gap-3"><LockKeyhole size={17}/> Continue with Google</span><ArrowUpRight size={16}/></a> : <div className="mt-7 rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm font-semibold text-amber-950">Sign-in needs setup</p><p className="mt-1 text-xs leading-5 text-amber-900">Set `GOOGLE_CLIENT_ID`, `GOOGLE_CLIENT_SECRET`, `DATABASE_URL` and `SESSION_SECRET` in `server/.env`, then restart the API.</p></div>}<p className="mt-6 text-center text-xs leading-5 text-slate-400">Google verifies your identity. Strive stores your account and training profile.</p></div></Card></main>;
}
