import { ArrowUpRight, Menu, MoveUpRight, X } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";


export function Navbar() {
  const [open, setOpen] = useState(false);
  return <header className="relative z-20 border-b border-slate-200/70 bg-[#f5f7f2]/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link to="/" className="flex items-center gap-2 font-bold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-950 text-lg text-lime-300">S</span><span>strive<span className="text-lime-700">.</span></span></Link><nav className="hidden items-center gap-8 text-sm font-medium text-slate-600 md:flex" aria-label="Main navigation"><a href="/#platform" className="hover:text-slate-950">Platform</a><a href="/#sports" className="hover:text-slate-950">Sports</a><a href="/#approach" className="hover:text-slate-950">Our approach</a></nav><div className="hidden items-center gap-3 md:flex"><Link to="/login" className="px-3 py-2 text-sm font-semibold">Log in</Link><Link to="/onboarding" className="inline-flex items-center gap-2 rounded-full bg-lime-300 px-5 py-3 text-sm font-semibold text-slate-950 transition hover:bg-lime-200">Get started <ArrowUpRight size={16}/></Link></div><button className="rounded-full p-2 md:hidden" aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div>{open && <nav className="absolute inset-x-0 top-full grid gap-1 border-b border-slate-200 bg-[#f5f7f2] p-5 shadow-lg md:hidden" aria-label="Mobile navigation"><a className="rounded-xl p-3" href="/#platform" onClick={() => setOpen(false)}>Platform</a><a className="rounded-xl p-3" href="/#sports" onClick={() => setOpen(false)}>Sports</a><Link className="rounded-xl p-3" to="/login" onClick={() => setOpen(false)}>Log in</Link><Link className="rounded-xl p-3 font-semibold" to="/onboarding" onClick={() => setOpen(false)}>Get started <MoveUpRight className="inline" size={15}/></Link></nav>}</header>;
}
