import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes } from "react";
import { LoaderCircle } from "lucide-react";

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> { variant?: "primary" | "secondary" | "ghost"; children: ReactNode }
export function Button({ variant = "primary", className = "", children, ...props }: ButtonProps) {
  const styles = { primary: "bg-lime-300 text-slate-950 hover:bg-lime-200", secondary: "border border-slate-200 bg-white text-slate-900 hover:bg-slate-50", ghost: "text-slate-600 hover:bg-slate-100" };
  return <button className={`inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition focus:outline-none focus:ring-2 focus:ring-lime-500 disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`} {...props}>{children}</button>;
}
export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`rounded-3xl border border-slate-200/80 bg-white shadow-sm ${className}`}>{children}</div>; }
interface InputProps extends InputHTMLAttributes<HTMLInputElement> { label?: string }
export function Input({ label, id, className = "", ...props }: InputProps) { return <div className="space-y-2">{label && <label htmlFor={id} className="block text-sm font-medium text-slate-700">{label}</label>}<input id={id} className={`w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none placeholder:text-slate-400 focus:border-lime-600 focus:ring-2 focus:ring-lime-100 ${className}`} {...props}/></div>; }
interface SelectProps extends SelectHTMLAttributes<HTMLSelectElement> { label?: string }
export function Select({ label, id, className = "", children, ...props }: SelectProps) { return <div className="space-y-2">{label && <label htmlFor={id} className="block text-sm font-medium text-slate-700">{label}</label>}<select id={id} className={`w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-lime-600 focus:ring-2 focus:ring-lime-100 ${className}`} {...props}>{children}</select></div>; }
export function Badge({ children, className = "" }: { children: ReactNode; className?: string }) { return <span className={`inline-flex items-center rounded-full bg-lime-100 px-3 py-1 text-xs font-semibold text-lime-900 ${className}`}>{children}</span>; }
export function ProgressBar({ value, label }: { value: number; label?: string }) { return <div className="space-y-2" aria-label={label}><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-lime-400" style={{ width: `${Math.max(0, Math.min(100, value))}%` }}/></div>{label && <span className="text-xs text-slate-500">{label}</span>}</div>; }
export function Modal({ open, title, onClose, children }: { open: boolean; title: string; onClose: () => void; children: ReactNode }) { if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby="modal-title" className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-xl"><div className="mb-4 flex items-center justify-between"><h2 id="modal-title" className="text-lg font-semibold">{title}</h2><button aria-label="Close dialog" onClick={onClose} className="rounded-full px-3 py-1 text-slate-500 hover:bg-slate-100">×</button></div>{children}</section></div>; }
export function LoadingSpinner({ label = "Loading" }: { label?: string }) { return <div className="flex items-center gap-2 text-sm text-slate-500" role="status"><LoaderCircle className="h-4 w-4 animate-spin" aria-hidden="true"/>{label}</div>; }
export function ErrorMessage({ message }: { message: string }) { return <p className="rounded-xl bg-red-50 p-4 text-sm text-red-800" role="alert">{message}</p>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center"><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm text-slate-500">{description}</p></div>; }
